theme: jekyll-theme-dinky
title: SHAPE
alt_title: SHAPE @ Florida Poly
description: SHAPE is a club at Florida Polytechnic University. We help you make cool things.
github:
    is_user_page: false
    is_project_page: false
